'use strict';

/* eslint-env node */

module.exports = {
  location: [
    'a bachelor pad',
    'a back room poker game',
    'a balcony',
    'a ball pit',
    'a bank vault',
    'a bank',
    'a basement',
    'a beach',
    'a bedroom',
    'a bike rack',
    'a bike shop',
    'a billiard room',
    'a bird sanctuary',
    'a booth at a convention',
    'a botanical garden',
    'a bowling alley',
    'a boxing ring',
    'a brewery',
    'a broadway star\'s dressing room',
    'a bus stop',
    'a butcher\'s shop',
    'a castle',
    'a cafe',
    'a campsite',
    'a candy store',
    'a car showroom',
    'a chemistry lab',
    'a classroom',
    'a convenience store',
    'a courtroom',
    'a craft beer pub',
    'a dance hall',
    'a dark alley',
    'a dark cave',
    'a dive bar',
    'a doctor\'s office',
    'a dorm room',
    'a driveway',
    'a fallout shelter',
    'a fancy restaurant',
    'a fashion studio',
    'a flea market',
    'a florist shop',
    'a food truck',
    'a funeral home',
    'a gaming store',
    'a golf course',
    'a green house',
    'a greenhouse',
    'a hair salon',
    'a hay loft',
    'a hobo\'s box car',
    'a horse-drawn carriage',
    'a hospital chapel',
    'a hot dog stand',
    'a hot tub',
    'a hotel lobby',
    'a hotel lobby',
    'a jail cell',
    'a jeweler\'s shop',
    'a kennel',
    'a kitchen',
    'a lan party',
    'a lawyer\'s office',
    'a library',
    'a life raft',
    'a liquor store',
    'a locker room',
    'a man cave',
    'a manhattan apartment',
    'a meat locker',
    'a mechanic\'s garage',
    'a military outpost',
    'a minivan',
    'a monastery',
    'a morgue',
    'a mountaintop hermitage',
    'a movie set',
    'a movie star\'s trailer',
    'a moving van',
    'a museum storage room',
    'a museum',
    'a particle physics lab',
    'a penthouse apt',
    'a photo booth',
    'a playground',
    'a playground',
    'a private jet',
    'a projection room',
    'a public swimming pool',
    'a radio booth',
    'a rec room',
    'a record store',
    'a recording studio',
    'a rooftop farm',
    'a rowboat',
    'a run-down apt',
    'a safe room',
    'a saloon',
    'a sauna',
    'a secluded beach',
    'a shipping container',
    'a shoe store',
    'a skate park',
    'a skating rink',
    'a ski lodge',
    'a stasis chamber',
    'a submarine',
    'a subway car',
    'a sweat shop',
    'a swimming pool',
    'a tailor\'s',
    'a taxi',
    'a tea house',
    'a teacher\'s lounge',
    'a tennis court',
    'a throne room',
    'a tiny cottage',
    'a torture chamber',
    'a trailer home',
    'a waiting room',
    'a walk-in closet',
    'a walk-in freezer',
    'a weight room',
    'a whitewater raft',
    'a wine cellar',
    'a workshop',
    'a world war one trench',
    'a yoga class',
    'an abandoned home',
    'an airlock',
    'an airplane cockpit',
    'an airport lounge',
    'an airport terminal gate',
    'an ambulance',
    'an antarctic research outpost',
    'an antiques store',
    'an apollo capsule',
    'an arcade',
    'an artist\'s studio',
    'an attic',
    'an english pub',
    'an executive office',
    'an ice fishing shack',
    'an observatory',
    'an operating room',
    'cold storage',
    'high school hall lockers',
    'hyperdrive cavity',
    'on a bus',
    'someone\'s garage',
    'the back of a limo',
    'the bridge of a spaceship',
    'the changing room at a store',
    'the chess club',
    'the deck of a boat',
    'the gym',
    'the kids table',
    'the ladies restroom',
    'the men\'s restroom',
    'the oval office',
    'the registrar\'s office',
    'the roof of a house',
    'the stables',
    'the VIP lounge',
    'the zoo',
    'a vintage shop'
  ],
  relationship: [
    'airplane passengers',
    'ambassador and king',
    'archivist and researcher',
    'arms dealer and parent',
    'astronaut and mission chief',
    'astronomer and meteor',
    'author and editor',
    'baby and pet',
    'babysitter and new parent',
    'bartender and regular',
    'bartender and waitress',
    'bear and cub',
    'bicyclist and driver',
    'blacksmith and jockey',
    'boss and brown-noser',
    'bride and wedding planner',
    'buggy driver and car owner',
    'bus driver and a regular',
    'cashier and customer',
    'castaway and coconut',
    'chef and maitre\'d',
    'child and parent',
    'coach and referee',
    'con man and sucker',
    'conductor and first violin',
    'cook and sous-chef',
    'dentist and patient',
    'dictator and general',
    'doctor and assassin',
    'dog food chef and cat food chef',
    'EMT and cop',
    'entrepreneur and bank officer',
    'executive and assistant',
    'farmer and scarecrow',
    'fishing boat captain and 1st mate',
    'foreman and architect',
    'forest ranger and camper',
    'forger and crime boss',
    'foster parent and teen',
    'gardener and pool boy',
    'hairdresser and regular',
    'hobo and street vendor',
    'hostage and robber',
    'jockey and vet',
    'journalist and informant',
    'landscaper and homeowner',
    'limo driver and trophy spouse',
    'logger and forest ranger',
    'mayor and janitor',
    'midwife and expecting mother',
    'millionaire and yacht salesperson',
    'mountain climbers',
    'museum curator and politician',
    'newlywed and bellhop',
    'nurse and recovering patient',
    'optometrist and patient',
    'parent and grandparent',
    'party animal and cop',
    'person and future self',
    'pet groomer and pet owner',
    'pharmacist and customer',
    'photographer and subject',
    'physical trainer and actor',
    'physicist and mathematician',
    'piano tuner and conceptual artist',
    'pilot and air traffic control tower',
    'pitcher and catcher',
    'postal worker and UPS delivery driver',
    'prince or princess and stable hand',
    'principal and teacher',
    'professor and star pupil',
    'programmer and student',
    'rare book collectors',
    'rival explorers',
    'robot and its creator',
    'sailor and lighthouse keeper',
    'school bus driver and the last kid',
    'scriptwriter and actor',
    'sculptor and model',
    'security guard and janitor',
    'senator and lobbyist',
    'skateboard salesperson and teen',
    'socialite and plumber',
    'spaceship pilot and artificial intelligence',
    'spouse and homewrecker',
    'spouse and parent-in-law',
    'spy and handler',
    'street hustler and off-duty cop',
    'student and rich relative',
    'stunt driver and director',
    'supervillain and prison guard',
    'tailor and cobbler',
    'tattoo artist and piercer',
    'taxi driver and passenger',
    'team owner and superstar',
    'teenager and grandparent',
    'teenager and mentor',
    'teenager and parent',
    'telephone operator and caller',
    'ticket agent and traveler',
    'torturer and jester',
    'traveler and translator',
    'two judges',
    'two shoe designers',
    'union leader and CEO',
    'vampire and werewolf',
    'watchmaker and apprentice',
    'woodsman and camper',
    'x-ray technician and doctor'
  ],
  occupation: [
    'actor',
    'acrobat',
    'ambassador',
    'animal keeper',
    'animator',
    'architect',
    'astronaut',
    'auctioneer',
    'baker',
    'barista',
    'bartender',
    'beautician',
    'bee-keeper',
    'bicycle messenger',
    'biologist',
    'body guard',
    'bookseller',
    'bouncer',
    'boxer',
    'bricklayer',
    'butcher',
    'call-center agent',
    'cameraman',
    'captain',
    'carpenter',
    'cemetery gardener',
    'chancellor',
    'chef',
    'chemist',
    'chimney sweep',
    'circus clown',
    'coder',
    'composer',
    'computer scientist',
    'concrete worker',
    'conductor',
    'creative director',
    'curator',
    'dentist',
    'diet counselor',
    'director',
    'disc jockey',
    'dog walker',
    'doorkeeper',
    'dragon slayer',
    'dressmaker',
    'driving instructor',
    'educator',
    'electrician',
    'embalmer',
    'energy consultant',
    'estate agent',
    'event manager',
    'fashion designer',
    'firefighter',
    'florist',
    'football player',
    'garbage man',
    'gardener',
    'geriatric nurse',
    'goldsmith',
    'grave digger',
    'headhunter',
    'high school teacher',
    'housewife or househusband',
    'human resources manager',
    'hunter',
    'ice-cream vendor',
    'interior designer',
    'interpreter',
    'jazz musician',
    'jockey',
    'journalist',
    'judge',
    'lawyer',
    'librarian',
    'lifeguard',
    'lobbyist',
    'mail carrier',
    'market researcher',
    'marriage counselor',
    'masseur',
    'meteorologist',
    'minister of defense',
    'model',
    'mountaineer',
    'music teacher',
    'ninja',
    'nuclear physicist',
    'nurse',
    'obstetrician',
    'optometrist',
    'painter',
    'pathologist',
    'pediatrician',
    'personal trainer',
    'pharmacist',
    'photographer',
    'physician',
    'physicist',
    'pianist',
    'piano maker',
    'pilot',
    'plumber',
    'priest',
    'prime minister',
    'private detective',
    'professor',
    'puppeteer',
    'race car driver',
    'rocket scientist',
    'roofer',
    'salesperson',
    'mall santa',
    'sculptor',
    'seamstress',
    'shepherd',
    'shipbuilder',
    'soccer referee',
    'sous chef',
    'speech writer',
    'sports instructor',
    'stage manager',
    'stonemason',
    'stunt man',
    'superhero',
    'swimming pool attendant',
    'taxi driver',
    'taxidermist',
    'teacher\'s assistant',
    'telemarketer',
    'therapist',
    'tour guide',
    'welder',
    'train driver',
    'veterinarian',
    'violin-maker',
    'watchmaker'
  ]
};
